version: '3.7'
services:
  cs_postgres:
    image: postgres:12.4-alpine
    ports:
      - 5432:5432
    volumes:
      - ./database/postgres:/var/lib/postgresql/data:delegated
    restart: always
    env_file:
      - ./.env

  api_exercise:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - cs_postgres
