services:

  cs-db:
    container_name: cs_postgres.local
    image: postgres:13.1
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - 5432:5432
    volumes:
      - ./sql/createDB.sql:/docker-entrypoint-initdb.d/createDB.sql
    networks:
      - esnet

  cs-web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - DATABASE_HOST=cs_postgres.local
    links:
      - cs-db
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet: