# Generated by Django 3.0.3 on 2021-02-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="dishes",
            field=models.ManyToManyField(blank=True, related_name="dishes", to="api.Dish"),
        ),
    ]
