# Generated by Django 3.0.3 on 2021-03-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_menu_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='preparation_time',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
