# Generated by Django 3.0.3 on 2021-03-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210309_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='add_date',
            new_name='added_on',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='update_date',
            new_name='update_on',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='add_date',
            new_name='added_on',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='update_date',
            new_name='update_on',
        ),
    ]
